const wordData = {
  ProgrammingLanguage: [
    "java",
    "c",
    "ruby",
    "perl",
    "python",
    "r",
    "javascript",
    "css",
    "html",
    "php",
    "sql",
    "mysql",
    "cobol",
    "scala",
    "abap",
    "xml",
    "kotlin",
    "matlab",
    "pascal",
    "typescript",
  ],
  Fruit: [
    "apple",
    "banana",
    "orange",
    "strawberry",
    "mango",
    "pineapple",
    "watermelon",
    "grape",
    "kiwi",
    "blueberry",
    "peach",
    "lemon",
    "cherry",
    "raspberry",
    "papaya",
    "plum",
    "cranberry",
    "pear",
    "apricot",
    "avocado",
  ],
  Animal: [
    "dog",
    "cat",
    "elephant",
    "lion",
    "tiger",
    "giraffe",
    "kangaroo",
    "horse",
    "zebra",
    "rabbit",
    "penguin",
    "dolphin",
    "bear",
    "crocodile",
    "gorilla",
    "cheetah",
    "koala",
    "rhinoceros",
    "ostrich",
    "chimpanzee",
  ],
  Flower: [
    "rose",
    "tulip",
    "sunflower",
    "orchid",
    "lily",
    "daisy",
    "lavender",
    "pansy",
    "poppy",
    "daffodil",
    "marigold",
    "hydrangea",
    "carnation",
    "jasmine",
    "iris",
    "chrysanthemum",
    "peony",
    "violet",
    "geranium",
    "honeysuckle",
  ],
  Clothes: [
    "shirt",
    "trousers",
    "dress",
    "jacket",
    "sweater",
    "skirt",
    "shorts",
    "blouse",
    "socks",
    "jeans",
    "suit",
    "hoodie",
    "coat",
    "tie",
    "cardigan",
    "leggings",
    "vest",
    "pajamas",
    "scarf",
    "hat",
  ],
  Country: [
    "USA",
    "Canada",
    "United Kingdom",
    "France",
    "Germany",
    "Australia",
    "Japan",
    "Brazil",
    "India",
    "China",
    "South Africa",
    "Spain",
    "Italy",
    "Mexico",
    "Russia",
    "Argentina",
    "Turkey",
    "Egypt",
    "Greece",
    "Sweden",
  ],
  Sport: [
    "soccer",
    "basketball",
    "tennis",
    "swimming",
    "volleyball",
    "baseball",
    "golf",
    "cricket",
    "rugby",
    "table tennis",
    "badminton",
    "wrestling",
    "athletics",
    "ice hockey",
    "gymnastics",
    "cycling",
    "boxing",
    "surfing",
    "skiing",
    "archery",
  ],
  Vegetable: [
    "tomato",
    "potato",
    "carrot",
    "broccoli",
    "cucumber",
    "spinach",
    "bell pepper",
    "cauliflower",
    "eggplant",
    "zucchini",
    "onion",
    "radish",
    "cabbage",
    "lettuce",
    "pumpkin",
    "sweet potato",
    "peas",
    "corn",
    "asparagus",
    "brussels sprouts",
  ],
  Vehicle: [
    "car",
    "bicycle",
    "bus",
    "train",
    "motorcycle",
    "truck",
    "ship",
    "helicopter",
    "airplane",
    "scooter",
    "tram",
    "skateboard",
    "canoe",
    "submarine",
    "jet ski",
    "rocket",
    "tugboat",
    "balloon",
    "segway",
    "cable car",
  ],
  Color: [
    "red",
    "blue",
    "green",
    "yellow",
    "pink",
    "purple",
    "brown",
    "black",
    "white",
    "orange",
    "gray",
    "silver",
    "gold",
    "maroon",
    "teal",
    "lavender",
    "indigo",
    "turquoise",
    "beige",
    "coral",
  ],
  Device: [
    "computer",
    "smartphone",
    "laptop",
    "tablet",
    "keyboard",
    "mouse",
    "monitor",
    "printer",
    "router",
    "camera",
    "headphones",
    "microphone",
    "software",
    "hardware",
    "server",
    "database",
    "internet",
    "coding",
    "algorithm",
    "artificial intelligence",
  ],
};

function randomWord(category) {
  const categories = Object.keys(wordData);
  const selectedCategory = category || categories[Math.floor(Math.random() * categories.length)];
  const wordsInCategory = wordData[selectedCategory];

  return {
    category: selectedCategory,
    word: wordsInCategory[Math.floor(Math.random() * wordsInCategory.length)],
  };
}

export { randomWord };
